### ISSUE TITLE
Doubt example for index.json

### ISSUE THREAD

**Issue by beckmx** [lbwa/google-smart-home#23]
Hello, I was reading your readmes, but it is only mentioned that it is needed the API key, do you have an example of where to export the index.json that contains all the data needed in config.default.ts?

**Comment by lbwa** [comment]
`index.json` include all your private configuration. You can refer to the following structure:

```js
{
  "oauth_client_id": "xxxxxx",
  "oauth_client_secret": "xxxxx",
  "google_project_id": "xxxx",
  "google_api_key": "xxxx"
}
```
